// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nexus.Config.Database;

#nullable disable

namespace nexus.Migrations
{
    [DbContext(typeof(Connection))]
    [Migration("20240804103231_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("nexus.Modules.Category.Entity.Categories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df105327-3a71-431c-b8ca-b2a4a3065b45"),
                            CreatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 43, DateTimeKind.Utc).AddTicks(9150),
                            Name = "MMORPG",
                            UpdatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 43, DateTimeKind.Utc).AddTicks(9152)
                        });
                });

            modelBuilder.Entity("nexus.Modules.Comment.Entity.Comments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("nexus.Modules.Post.Entity.Posts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("article");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("716f93dc-23e4-40f1-b0ef-f715416689f1"),
                            Article = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            CategoryId = new Guid("df105327-3a71-431c-b8ca-b2a4a3065b45"),
                            CreatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(4383),
                            Slug = "article-test-8DCB470BED09258",
                            Status = "published",
                            Title = "Article Test",
                            UpdatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(4384),
                            UserId = new Guid("a25881b1-d522-4a71-b889-724da3084a81")
                        },
                        new
                        {
                            Id = new Guid("e27daea5-d7af-4e98-aced-e4d7be1dc490"),
                            Article = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            CategoryId = new Guid("df105327-3a71-431c-b8ca-b2a4a3065b45"),
                            CreatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(4652),
                            Slug = "article-test-8DCB470BED09284",
                            Status = "published",
                            Title = "Article Test",
                            UpdatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(4652),
                            UserId = new Guid("a25881b1-d522-4a71-b889-724da3084a81")
                        },
                        new
                        {
                            Id = new Guid("e381d2b7-7e50-407b-a6da-8508046c8cb9"),
                            Article = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            CategoryId = new Guid("df105327-3a71-431c-b8ca-b2a4a3065b45"),
                            CreatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(4679),
                            Slug = "article-test-8DCB470BED09295",
                            Status = "published",
                            Title = "Article Test",
                            UpdatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(4679),
                            UserId = new Guid("a25881b1-d522-4a71-b889-724da3084a81")
                        },
                        new
                        {
                            Id = new Guid("571f9934-c988-499b-b356-3c12215ab360"),
                            Article = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            CategoryId = new Guid("df105327-3a71-431c-b8ca-b2a4a3065b45"),
                            CreatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(4695),
                            Slug = "article-test-8DCB470BED092A2",
                            Status = "published",
                            Title = "Dummy Article",
                            UpdatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(4695),
                            UserId = new Guid("a25881b1-d522-4a71-b889-724da3084a81")
                        });
                });

            modelBuilder.Entity("nexus.Modules.Role.Entity.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("774a46c6-ea74-48f8-8451-11dfddd405ce"),
                            CreatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(2692),
                            Name = "Admin",
                            Status = "active",
                            UpdatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(2693)
                        },
                        new
                        {
                            Id = new Guid("c0a3574d-b205-431c-a6fa-7bd8b138d610"),
                            CreatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(2696),
                            Name = "User",
                            Status = "active",
                            UpdatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(2696)
                        });
                });

            modelBuilder.Entity("nexus.Modules.User.Entity.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<long>("Nik")
                        .HasColumnType("bigint")
                        .HasColumnName("nik");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nik")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a25881b1-d522-4a71-b889-724da3084a81"),
                            CreatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(7191),
                            Email = "admin@gmail.com",
                            Fullname = "Administrator",
                            Nik = 76247031L,
                            Password = "$2a$11$wW2WZ8q5uGK4IHfLnO2TDuN4PPYmvW4JrPGkSiqMWtAPvNBbn8LJa",
                            RoleId = new Guid("774a46c6-ea74-48f8-8451-11dfddd405ce"),
                            Status = "active",
                            UpdatedAt = new DateTime(2024, 8, 4, 10, 32, 31, 44, DateTimeKind.Utc).AddTicks(7191),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("nexus.Modules.Comment.Entity.Comments", b =>
                {
                    b.HasOne("nexus.Modules.Post.Entity.Posts", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.HasOne("nexus.Modules.User.Entity.Users", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nexus.Modules.Post.Entity.Posts", b =>
                {
                    b.HasOne("nexus.Modules.Category.Entity.Categories", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId");

                    b.HasOne("nexus.Modules.User.Entity.Users", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nexus.Modules.User.Entity.Users", b =>
                {
                    b.HasOne("nexus.Modules.Role.Entity.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("nexus.Modules.Category.Entity.Categories", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("nexus.Modules.Post.Entity.Posts", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("nexus.Modules.Role.Entity.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("nexus.Modules.User.Entity.Users", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
